
server:
  port: 8083

spring:
  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/profiledb?autoReconnect=true&useSSL=false
    username: root
    password: root
    database: profildb